# Generated by Django 4.1.7 on 2023-08-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_admin'),
        ('customer', '0002_remove_cart_seller_cart_product_alter_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('pincode', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
            ],
        ),
    ]
