# Generated by Django 4.1.7 on 2023-08-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
