# Generated by Django 4.1.5 on 2023-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_description', models.CharField(max_length=50)),
                ('p_category', models.CharField(max_length=50)),
                ('p_number', models.BigIntegerField()),
                ('p_stock', models.BigIntegerField()),
                ('p_price', models.BigIntegerField()),
                ('p_image', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
