# Generated by Django 4.1.5 on 2023-03-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
