# Generated by Django 4.1.7 on 2023-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_table'),
        ('seller', '0006_alter_product_table'),
    ]

    operations = [
    ]
