# Generated by Django 4.1.7 on 2023-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_username', models.CharField(max_length=50)),
                ('a_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
