# Generated by Django 4.1.7 on 2023-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_phone_number_customers_mobile_number_and_more'),
        ('common', '0006_alter_customers_mobile_number'),
        ('common', '0006_seller_s_status'),
    ]

    operations = [
    ]
