# Generated by Django 4.1.7 on 2023-03-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0002_users_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
